version: '3.7'

services:
  working:
    build: ./working
    volumes:
      - ./storage:/storage
    command: ["tail", "-f", "/dev/null"]

  mysql:
    build: ./sql
    volumes:
      - ./sql:/root/sql
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'p@ssword'

  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"

volumes:
    db_data: {}